version: '2'
services:
  allowd:
    image: allowd:latest
    command: node _build
    depends_on:
      - redis
      - statsd
    links:
      - redis
      - statsd
    environment:
      REDIS_URIS: redis:6379
      LOG_LEVEL: debug
      STATSD_URIS: statsd:8125
    restart: always
  redis:
    image: redis:alpine
    restart: always
    ports:
      - 6379
  statsd:
    image: kamon/grafana_graphite
    ports:
      - 80
      - 8125/udp
